In [1]:
'hello'.upper()

'HELLO'

In [2]:
import pandas as pd

In [3]:
orders = pd.read_table('http://bit.ly/chiporders')

In [4]:
orders.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [5]:
 orders['item_name'].str.upper()

0                CHIPS AND FRESH TOMATO SALSA
1                                        IZZE
2                            NANTUCKET NECTAR
3       CHIPS AND TOMATILLO-GREEN CHILI SALSA
4                                CHICKEN BOWL
                        ...
4617                            STEAK BURRITO
4618                            STEAK BURRITO
4619                       CHICKEN SALAD BOWL
4620                       CHICKEN SALAD BOWL
4621                       CHICKEN SALAD BOWL
Name: item_name, Length: 4622, dtype: object

In [6]:
orders[orders['item_name'].str.contains('Burrito')]

,order_id,quantity,item_name,choice_description,item_price
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
31,16,1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$8.99
43,20,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$11.75
45,21,1,Chicken Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$10.98
46,21,1,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...",$8.99
48,22,1,Steak Burrito,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99
50,23,1,Steak Burrito,"[Roasted Chili Corn Salsa (Medium), [Rice, Faj...",$8.99
52,24,1,Chicken Burrito,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$10.98
57,26,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
63,28,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",$8.75
64,29,1,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99
67,30,1,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Cheese]]",$8.99
68,30,1,Chicken Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$10.98
69,31,1,Steak Burrito,"[Roasted Chili Corn Salsa (Medium), [Rice, Bla...",$8.99
71,32,1,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99
73,33,1,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
81,36,1,Barbacoa Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.25
82,36,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
83,37,1,Chicken Burrito,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
88,39,1,Carnitas Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",$9.25
93,41,1,Carnitas Burrito,"[Roasted Chili Corn Salsa, [Sour Cream, Guacam...",$11.75
98,43,1,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
101,45,1,Steak Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Rice, ...",$8.99
...,...,...,...,...,...
4473,1783,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$9.25
4478,1785,1,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice]]",$8.75
4482,1786,1,Carnitas Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.75
4487,1786,1,Carnitas Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Guaca...",$11.75
4492,1787,1,Chicken Burrito,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
4508,1793,1,Steak Burrito,[Brown Rice],$8.99
4519,1797,1,Veggie Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Cheese]]",$8.75
4521,1798,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Guacamole, Lettuce...",$11.25
4524,1799,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
4528,1800,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$8.75
4530,1801,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
4533,1802,1,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4536,1803,1,Steak Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4543,1806,1,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice]]",$8.75
4546,1807,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",$9.25
4556,1811,1,Chicken Burrito,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$11.25
4558,1812,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4559,1812,1,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Gua...",$11.25
4566,1816,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Pinto Beans, Chees...",$8.75
4569,1817,1,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice]]",$8.75
4578,1821,1,Carnitas Burrito,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",$9.25
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$11.75
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",$11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75

In [7]:
orders.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [8]:
orders['choice_description'].str.replace('[', '')

0                                                     NaN
1                                             Clementine]
2                                                  Apple]
3                                                     NaN
4       Tomatillo-Red Chili Salsa (Hot), Black Beans, ...
                              ...
4617    Fresh Tomato Salsa, Rice, Black Beans, Sour Cr...
4618    Fresh Tomato Salsa, Rice, Sour Cream, Cheese, ...
4619    Fresh Tomato Salsa, Fajita Vegetables, Pinto B...
4620     Fresh Tomato Salsa, Fajita Vegetables, Lettuce]]
4621    Fresh Tomato Salsa, Fajita Vegetables, Pinto B...
Name: choice_description, Length: 4622, dtype: object

In [9]:
orders['choice_description'].str.replace(']', '')

0                                                     NaN
1                                             [Clementine
2                                                  [Apple
3                                                     NaN
4       [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
                              ...
4617    [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...
4618    [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...
4619    [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...
4620     [Fresh Tomato Salsa, [Fajita Vegetables, Lettuce
4621    [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...
Name: choice_description, Length: 4622, dtype: object

In [10]:
orders.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [11]:
orders['choice_description'].str.replace('[', '').str.replace(']', '')

0                                                     NaN
1                                              Clementine
2                                                   Apple
3                                                     NaN
4       Tomatillo-Red Chili Salsa (Hot), Black Beans, ...
                              ...
4617    Fresh Tomato Salsa, Rice, Black Beans, Sour Cr...
4618    Fresh Tomato Salsa, Rice, Sour Cream, Cheese, ...
4619    Fresh Tomato Salsa, Fajita Vegetables, Pinto B...
4620       Fresh Tomato Salsa, Fajita Vegetables, Lettuce
4621    Fresh Tomato Salsa, Fajita Vegetables, Pinto B...
Name: choice_description, Length: 4622, dtype: object

In [ ]:
orders['choice_description'].str.replace('[', '').str.replace(']', '')