In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('http://bit.ly/imdbratings')

In [3]:
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [4]:
movies.content_rating.isnull().sum()

3

In [5]:
movies[movies.content_rating.isnull()]

,star_rating,title,content_rating,genre,duration,actors_list
187,8.2,Butch Cassidy and the Sundance Kid,NaN,Biography,110,"[u'Paul Newman', u'Robert Redford', u'Katharin..."
649,7.7,Where Eagles Dare,NaN,Action,158,"[u'Richard Burton', u'Clint Eastwood', u'Mary ..."
936,7.4,True Grit,NaN,Adventure,128,"[u'John Wayne', u'Kim Darby', u'Glen Campbell']"

In [6]:
movies.content_rating.value_counts()

R            460
PG-13        189
PG           123
NOT RATED     65
APPROVED      47
UNRATED       38
G             32
NC-17          7
PASSED         7
X              4
GP             3
TV-MA          1
Name: content_rating, dtype: int64

In [7]:
movies[movies.content_rating=='NOT RATED']

,star_rating,title,content_rating,genre,duration,actors_list
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
41,8.5,Sunset Blvd.,NOT RATED,Drama,110,"[u'William Holden', u'Gloria Swanson', u'Erich..."
63,8.4,M,NOT RATED,Crime,99,"[u'Peter Lorre', u'Ellen Widmann', u'Inge Land..."
66,8.4,Munna Bhai M.B.B.S.,NOT RATED,Comedy,156,"[u'Sunil Dutt', u'Sanjay Dutt', u'Arshad Warsi']"
72,8.4,Rang De Basanti,NOT RATED,Drama,157,"[u'Aamir Khan', u'Soha Ali Khan', u'Siddharth']"
83,8.4,To Kill a Mockingbird,NOT RATED,Drama,129,"[u'Gregory Peck', u'John Megna', u'Frank Overt..."
87,8.4,Bicycle Thieves,NOT RATED,Drama,93,"[u'Lamberto Maggiorani', u'Enzo Staiola', u'Li..."
88,8.4,The Kid,NOT RATED,Comedy,68,"[u'Charles Chaplin', u'Edna Purviance', u'Jack..."
89,8.4,Swades,NOT RATED,Drama,189,"[u'Shah Rukh Khan', u'Gayatri Joshi', u'Kishor..."
93,8.4,Dilwale Dulhania Le Jayenge,NOT RATED,Comedy,181,"[u'Shah Rukh Khan', u'Kajol', u'Amrish Puri']"
100,8.3,The Treasure of the Sierra Madre,NOT RATED,Action,126,"[u'Humphrey Bogart', u'Walter Huston', u'Tim H..."
104,8.3,Ikiru,NOT RATED,Drama,143,"[u'Takashi Shimura', u'Nobuo Kaneko', u""Shin'i..."
105,8.3,The Third Man,NOT RATED,Film-Noir,93,"[u'Orson Welles', u'Joseph Cotten', u'Alida Va..."
108,8.3,Metropolis,NOT RATED,Drama,153,"[u'Brigitte Helm', u'Alfred Abel', u'Gustav Fr..."
109,8.3,Dil Chahta Hai,NOT RATED,Comedy,183,"[u'Aamir Khan', u'Saif Ali Khan', u'Akshaye Kh..."
111,8.3,Some Like It Hot,NOT RATED,Comedy,120,"[u'Marilyn Monroe', u'Tony Curtis', u'Jack Lem..."
116,8.3,Mr. Smith Goes to Washington,NOT RATED,Drama,129,"[u'James Stewart', u'Jean Arthur', u'Claude Ra..."
122,8.3,On the Waterfront,NOT RATED,Crime,108,"[u'Marlon Brando', u'Karl Malden', u'Lee J. Co..."
128,8.3,The Gold Rush,NOT RATED,Adventure,95,"[u'Charles Chaplin', u'Mack Swain', u'Tom Murr..."
132,8.3,Judgment at Nuremberg,NOT RATED,Drama,186,"[u'Spencer Tracy', u'Burt Lancaster', u'Richar..."
133,8.3,Barfi!,NOT RATED,Adventure,151,"[u'Ranbir Kapoor', u'Priyanka Chopra', u'Ileana']"
134,8.3,The Seventh Seal,NOT RATED,Drama,96,"[u'Max von Sydow', u'Gunnar Bj\xf6rnstrand', u..."
140,8.3,The Wages of Fear,NOT RATED,Adventure,131,"[u'Yves Montand', u'Charles Vanel', u'Peter va..."
149,8.2,Rebecca,NOT RATED,Mystery,130,"[u'Laurence Olivier', u'Joan Fontaine', u'Geor..."
165,8.2,My Sassy Girl,NOT RATED,Comedy,123,"[u'Tae-hyun Cha', u'Gianna Jun', u'In-mun Kim']"
167,8.2,Mary and Max,NOT RATED,Animation,92,"[u'Toni Collette', u'Philip Seymour Hoffman', ..."
169,8.2,The Maltese Falcon,NOT RATED,Crime,100,"[u'Humphrey Bogart', u'Mary Astor', u'Gladys G..."
174,8.2,Persona,NOT RATED,Drama,83,"[u'Bibi Andersson', u'Liv Ullmann', u'Margaret..."
178,8.2,The 400 Blows,NOT RATED,Crime,99,"[u'Jean-Pierre L\xe9aud', u'Albert R\xe9my', u..."
...,...,...,...,...,...,...
215,8.1,La Strada,NOT RATED,Drama,108,"[u'Anthony Quinn', u'Giulietta Masina', u'Rich..."
231,8.1,La Dolce Vita,NOT RATED,Comedy,174,"[u'Marcello Mastroianni', u'Anita Ekberg', u'A..."
234,8.1,La Haine,NOT RATED,Crime,98,"[u'Vincent Cassel', u'Hubert Kound\xe9', u'Sa\..."
246,8.1,Stalag 17,NOT RATED,Comedy,120,"[u'William Holden', u'Don Taylor', u'Otto Prem..."
252,8.1,Arsenic and Old Lace,NOT RATED,Comedy,118,"[u'Cary Grant', u'Priscilla Lane', u'Raymond M..."
254,8.1,Roman Holiday,NOT RATED,Comedy,118,"[u'Gregory Peck', u'Audrey Hepburn', u'Eddie A..."
255,8.1,The Philadelphia Story,NOT RATED,Comedy,112,"[u'Cary Grant', u'Katharine Hepburn', u'James ..."
263,8.1,Rio Bravo,NOT RATED,Western,141,"[u'John Wayne', u'Dean Martin', u'Ricky Nelson']"
265,8.1,Harvey,NOT RATED,Comedy,104,"[u'James Stewart', u'Josephine Hull', u'Peggy ..."
315,8.0,Charade,NOT RATED,Comedy,113,"[u'Cary Grant', u'Audrey Hepburn', u'Walter Ma..."
328,8.0,"Aguirre, the Wrath of God",NOT RATED,Adventure,93,"[u'Klaus Kinski', u'Ruy Guerra', u'Helena Rojo']"
343,8.0,Ghost in the Shell,NOT RATED,Animation,83,"[u'Atsuko Tanaka', u'Iemasa Kayumi', u'Akio \x..."
405,7.9,The Bride of Frankenstein,NOT RATED,Horror,75,"[u'Boris Karloff', u'Elsa Lanchester', u'Colin..."
419,7.9,Stagecoach,NOT RATED,Adventure,96,"[u'John Wayne', u'Claire Trevor', u'Andy Devine']"
427,7.9,"4 Months, 3 Weeks and 2 Days",NOT RATED,Drama,113,"[u'Anamaria Marinca', u'Vlad Ivanov', u'Laura ..."
453,7.9,Toki o kakeru shojo,NOT RATED,Animation,98,"[u'Riisa Naka', u'Takuya Ishida', u'Mitsutaka ..."
478,7.8,I Saw the Devil,NOT RATED,Crime,141,"[u'Byung-hun Lee', u'Min-sik Choi', u'In-seo K..."
481,7.8,Evil,NOT RATED,Drama,113,"[u'Andreas Wilson', u'Henrik Lundstr\xf6m', u'..."
491,7.8,The Magnificent Seven,NOT RATED,Action,128,"[u'Yul Brynner', u'Steve McQueen', u'Charles B..."
528,7.8,From Here to Eternity,NOT RATED,Drama,118,"[u'Burt Lancaster', u'Montgomery Clift', u'Deb..."
531,7.8,The Dirty Dozen,NOT RATED,Action,150,"[u'Lee Marvin', u'Ernest Borgnine', u'Charles ..."
546,7.8,Breakfast at Tiffany's,NOT RATED,Comedy,115,"[u'Audrey Hepburn', u'George Peppard', u'Patri..."
573,7.8,Battle Royale,NOT RATED,Action,114,"[u'Tatsuya Fujiwara', u'Aki Maeda', u'Tar\xf4 ..."
592,7.7,Detachment,NOT RATED,Drama,98,"[u'Adrien Brody', u'Christina Hendricks', u'Ma..."
647,7.7,La grande bellezza,NOT RATED,Drama,142,"[u'Toni Servillo', u'Carlo Verdone', u'Sabrina..."
665,7.7,Lolita,NOT RATED,Drama,152,"[u'James Mason', u'Shelley Winters', u'Sue Lyon']"
673,7.7,Blow-Up,NOT RATED,Drama,111,"[u'David Hemmings', u'Vanessa Redgrave', u'Sar..."
763,7.6,Hunger,NOT RATED,Biography,96,"[u'Stuart Graham', u'Laine Megaw', u'Brian Mil..."
827,7.5,The Wind That Shakes the Barley,NOT RATED,Drama,127,"[u'Cillian Murphy', u'Padraic Delaney', u'Liam..."
899,7.5,In the Loop,NOT RATED,Comedy,106,"[u'Tom Hollander', u'Peter Capaldi', u'James G..."

In [8]:
movies[movies.content_rating=='NOT RATED'].content_rating

5      NOT RATED
6      NOT RATED
41     NOT RATED
63     NOT RATED
66     NOT RATED
         ...
665    NOT RATED
673    NOT RATED
763    NOT RATED
827    NOT RATED
899    NOT RATED
Name: content_rating, Length: 65, dtype: object

In [9]:
import numpy as np

In [10]:
movies[movies.content_rating=='NOT RATED'].content_rating = np.nan

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5209: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [11]:
movies.content_rating.isnull().sum()

3

In [12]:
movies.loc[movies.content_rating=='NOT RATED', 'content_rating'] = np.nan

In [13]:
movies.content_rating.isnull().sum()

68

In [14]:
top_movies = movies.loc[movies.star_rating >= 9, :]

In [15]:
top_movies

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."

In [16]:
top_movies.loc[0,'duration'] = 150

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:480: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [17]:
top_movies

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,150,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."

In [18]:
top_movies = movies.loc[movies.star_rating >= 9, :].copy()

In [19]:
top_movies.loc[0,'duration'] = 150

In [20]:
top_movies

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,150,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."

In [21]:
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."